### ISSUE TITLE
Proxy::refresh error on fresh install - Admin login

### ISSUE THREAD

**Issue by NZSAL** [condor2/Opencart_3031#1]
Notice: Undefined property: Proxy::refresh in /home/admin/web/domain.com/public_html/system/engine/action.php on line 79

**Comment by condor2** [comment]
I have restored old code.
I will do more tests

**Comment by condor2** [comment]
https://github.com/condor2/Opencart_3031/commit/cd05be632a1074cf3f1856b378a762617dfc5c2c
